### ISSUE TITLE
Crash on get theme settings

### ISSUE THREAD

**Issue by StabbarN** [ElMassimo/sublime-toggle-dark-mode#1]
It crashes on https://github.com/ElMassimo/sublime-toggle-dark-mode/blob/main/toggle_dark_mode.py#L25

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/xyz/Library/Application Support/Sublime Text/Installed Packages/Toggle Dark Mode.sublime-package/toggle_dark_mode.py", line 25
    theme = settings.get(f'{value}_theme')
```

No theme is set so the default values should work. 

```
	// Sets the colors used within the text area.
	// The value "auto" will switch between the "light_color_scheme" and
	// "dark_color_scheme" based on the operating system appearance.
	"color_scheme": "Mariana.sublime-color-scheme",

	// Controls the "color_scheme" when set to "auto"
	"light_color_scheme": "Breakers.sublime-color-scheme",
	"dark_color_scheme": "Mariana.sublime-color-scheme",
```
```
	// The theme controls the look of Sublime Text's UI (buttons, tabs, scroll
	// bars, etc)
	// The value "auto" will switch between the "light_theme" and "dark_theme"
	// based on the operating system appearance.
	"theme": "auto",

	// Controls the "theme" when to "auto"
	"light_theme": "Default.sublime-theme",
	"dark_theme": "Default Dark.sublime-theme",
```

I tried setting theme and color_scheme explicitly but to no avail.

Sublime version 4113.

**Comment by ElMassimo** [comment]
Hi @StabbarN! Thanks for reporting!

The error seems to be related with the fact that `f-Strings` were introduced in Python 3.6, so the plugin is failing to load under Python 3.3.

I changed the string interpolation to use the "old-style" `%` operator, and released `1.0.3`
